-- Crear una base de datos


DROP DATABASE VENTA2024;
GO

CREATE DATABASE VENTA2024;
GO


CREATE TABLE VENTA2024..CLIENTE(
	IDCLIENTE INT IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO VARCHAR(100) NOT NULL,
	CELULAR VARCHAR(20) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(IDCLIENTE)
);
GO

TRUNCATE TABLE VENTA2024..CLIENTE;
GO

INSERT INTO VENTA2024..CLIENTE(NOMBRE,APELLIDO,CELULAR,CORREO)
VALUES('GUSTAVO','CORONEL','999666777','GUSTAVO@GMAIL.COM');
GO

INSERT INTO VENTA2024..CLIENTE (NOMBRE,APELLIDO,CELULAR,CORREO)
VALUES('OSWALDO','RAMOS','947152186','OSWALDO@GMAIL.COM');
GO

INSERT INTO VENTA2024..CLIENTE(NOMBRE,APELLIDO,CELULAR,CORREO)
VALUES('DIEGUITO','TUTERROR','666666666','DIEGUITO@FRANKFURTEN.COM');
GO

INSERT INTO VENTA2024..CLIENTE(NOMBRE,APELLIDO,CELULAR,CORREO)
VALUES('DANIELITA','MASNAKI','987654321','DANIELITA@DANIELITA.COM');
GO

INSERT INTO VENTA2024..CLIENTE (NOMBRE,APELLIDO,CELULAR,CORREO)
VALUES ('JOSE','PALOMINO','987654321','JOSE@GMAIL.COM');
GO

SELECT * FROM VENTA2024..CLIENTE;
GO

CREATE TABLE VENTA2024..PRODUCTO(
	IDPRODUCTO INT IDENTITY(1,1),
	NOMBRE VARCHAR(150) NOT NULL,
	PRE_COMPRA NUMERIC(10,2) NOT NULL,
	PRE_VENTA NUMERIC(10,2) NOT NULL,
	STOCK INT NOT NULL,
	CONSTRAINT PK_PRODUCTO PRIMARY KEY(IDPRODUCTO),
	CONSTRAINT CHK_PRODUCTO_PRE_COMPRA CHECK(PRE_COMPRA>0.0),
	CONSTRAINT CHK_PRODUCTO_PRE_VENTA CHECK(PRE_VENTA>PRE_COMPRA),
	CONSTRAINT CHK_PRODUCTO_STOCK CHECK(STOCK>=0)
);
GO

TRUNCATE TABLE VENTA2024..PRODUCTO;
GO

INSERT INTO VENTA2024..PRODUCTO(NOMBRE,PRE_COMPRA,PRE_VENTA,STOCK)
VALUES('TELEVISOR DE 40 PULG',2500.00,4800.00,80);
GO

INSERT INTO VENTA2024..PRODUCTO (NOMBRE, PRE_COMPRA,PRE_VENTA, STOCK)
VALUES ('PS5', 5500.00, 7000.00, 100)
GO

INSERT INTO VENTA2024..PRODUCTO(NOMBRE,PRE_COMPRA,PRE_VENTA,STOCK)
VALUES ('BICICLETA MONTAÑERA',2300.00,5000.00,60);
GO

INSERT INTO VENTA2024..PRODUCTO(NOMBRE,PRE_COMPRA,PRE_VENTA,STOCK)
VALUES('PLUG',2500.00,4800.00,80);
GO


INSERT INTO VENTA2024..PRODUCTO (NOMBRE,PRE_COMPRA,PRE_VENTA,STOCK)
VALUES ('LAPTOPS',2500.00,4000.00,10);
GO


INSERT INTO VENTA2024..PRODUCTO (NOMBRE, PRE_COMPRA, PRE_VENTA, STOCK)
VALUES ('LÁMPARA LED', 150.00, 300.00, 120);
GO


INSERT INTO VENTA2024..PRODUCTO (NOMBRE, PRE_COMPRA, PRE_VENTA, STOCK)
VALUES ('REPRODUCTOR DE DVD', 500.00, 950.00, 50);
GO


INSERT INTO VENTA2024..PRODUCTO (NOMBRE, PRE_COMPRA, PRE_VENTA, STOCK)
VALUES ('TECLADO MECÁNICO', 200.00, 400.00, 75);
GO


INSERT INTO VENTA2024..PRODUCTO (NOMBRE, PRE_COMPRA, PRE_VENTA, STOCK)
VALUES ('MESA DE COMPUTADORA', 700.00, 1200.00, 30);
GO


INSERT INTO VENTA2024..PRODUCTO (NOMBRE, PRE_COMPRA, PRE_VENTA, STOCK)
VALUES ('SILLA ERGONÓMICA', 350.00, 650.00, 40);
GO


INSERT INTO VENTA2024..PRODUCTO (NOMBRE, PRE_COMPRA, PRE_VENTA, STOCK)
VALUES ('IMPRESORA LASER', 800.00, 1500.00, 20);
GO


INSERT INTO VENTA2024..PRODUCTO (NOMBRE, PRE_COMPRA, PRE_VENTA, STOCK)
VALUES ('ALTAVOCES BLUETOOTH', 100.00, 220.00, 90);
GO

INSERT INTO VENTA2024..PRODUCTO (NOMBRE, PRE_COMPRA, PRE_VENTA, STOCK)
VALUES ('MICRÓFONO USB', 120.00, 250.00, 60);
GO

INSERT INTO VENTA2024..PRODUCTO (NOMBRE, PRE_COMPRA, PRE_VENTA, STOCK)
VALUES ('CARGADOR INALÁMBRICO', 80.00, 180.00, 150);
GO


INSERT INTO VENTA2024..PRODUCTO (NOMBRE, PRE_COMPRA, PRE_VENTA, STOCK)
VALUES ('SOFÁ DE 3 PLAZAS', 2500.00, 5000.00, 15);
GO

SELECT * FROM VENTA2024..PRODUCTO;
GO


CREATE TABLE VENTA2024..VENTA(
	IDVENTA INT IDENTITY(1,1),
	FECHA DATETIME NOT NULL,
	IDCLIENTE INT NOT NULL,
	IMPORTE NUMERIC(10,2) NOT NULL DEFAULT 0.0,
	IMPUESTO NUMERIC(10,2) NOT NULL DEFAULT 0.0,
	TOTAL NUMERIC(10,2) NOT NULL DEFAULT 0.0,
	CONSTRAINT PK_VENTA PRIMARY KEY(IDVENTA),
	CONSTRAINT FK_VENTA_CLIENTE 
		FOREIGN KEY (IDCLIENTE) REFERENCES VENTA2024..CLIENTE(IDCLIENTE),
	CONSTRAINT CHK_VENTA_TOTAL CHECK(TOTAL = IMPORTE + IMPUESTO)
);
GO


TRUNCATE TABLE VENTA2024..VENTA;
GO

INSERT INTO VENTA2024..VENTA(FECHA,IDCLIENTE) VALUES(GETDATE()-40, 2);
INSERT INTO VENTA2024..VENTA(FECHA,IDCLIENTE) VALUES(GETDATE()-35, 1);
INSERT INTO VENTA2024..VENTA(FECHA,IDCLIENTE) VALUES(GETDATE()-30, 3);
INSERT INTO VENTA2024..VENTA(FECHA,IDCLIENTE) VALUES(GETDATE()-20, 2);
INSERT INTO VENTA2024..VENTA(FECHA,IDCLIENTE) VALUES(GETDATE()-10, 4);
GO

SELECT * FROM VENTA2024..VENTA;
GO


CREATE TABLE VENTA2024..DETALLE(
	IDVENTA INT,
	IDPRODUCTO INT,
	PRECIO NUMERIC(10,2) NOT NULL,
	CANTIDAD INT NOT NULL,
	SUBTOTAL NUMERIC(10,2) NOT NULL,
	CONSTRAINT PK_DETALLE PRIMARY KEY(IDVENTA,IDPRODUCTO),
	CONSTRAINT FK_DETALLE_VENTA
		FOREIGN KEY( IDVENTA) REFERENCES VENTA2024..VENTA(IDVENTA),
	CONSTRAINT FK_DETALLE_PRODUCTO 
		FOREIGN KEY(IDPRODUCTO) REFERENCES VENTA2024..PRODUCTO(IDPRODUCTO),
	CONSTRAINT CHK_DETALLE_SUBTOTAL CHECK(PRECIO*CANTIDAD=SUBTOTAL)
);
GO


TRUNCATE TABLE VENTA2024..DETALLE;
GO

-- VENTA 1
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(1,5,0,2,0);
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(1,10,0,4,0);
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(1,7,0,3,0);
GO

-- VENTA 2
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(2,3,0,2,0);
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(2,12,0,4,0);
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(2,9,0,3,0);
GO

-- VENTA 3
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(3,6,0,3,0);
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(3,9,0,2,0);
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(3,7,0,5,0);
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(3,8,0,6,0);
GO

-- VENTA 4
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(4,1,0,3,0);
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(4,3,0,2,0);
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(4,5,0,5,0);
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(4,7,0,6,0);
GO

-- VENTA 5
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(5,3,0,2,0);
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(5,8,0,4,0);
INSERT INTO VENTA2024..DETALLE(IDVENTA,IDPRODUCTO,PRECIO,CANTIDAD,SUBTOTAL) VALUES(5,9,0,3,0);
GO

SELECT * FROM VENTA2024..DETALLE;
GO


-- ACTUALIZANDO DATOS

SELECT * FROM VENTA2024..DETALLE;
GO

UPDATE VENTA2024..DETALLE
SET 
	PRECIO = P.PRE_VENTA,
	SUBTOTAL = P.PRE_VENTA * D.CANTIDAD
FROM VENTA2024..DETALLE D
JOIN VENTA2024..PRODUCTO P
ON D.IDPRODUCTO = P.IDPRODUCTO;
GO

SELECT * FROM VENTA2024..VENTA;
GO

ALTER TABLE VENTA2024..VENTA NOCHECK CONSTRAINT ALL;
GO

UPDATE VENTA2024..VENTA
SET TOTAL = (SELECT SUM(D.SUBTOTAL) FROM VENTA2024..DETALLE D
			  WHERE D.IDVENTA=V.IDVENTA)
FROM VENTA2024..VENTA V;
GO

UPDATE VENTA2024..VENTA
SET IMPORTE = TOTAL / 1.18;
GO

UPDATE VENTA2024..VENTA
SET IMPUESTO = TOTAL - IMPORTE;
GO

SELECT * FROM VENTA2024..VENTA;
GO


ALTER TABLE VENTA2024..VENTA CHECK CONSTRAINT ALL;
GO


