-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2024-09-11 03:03:14.647

-- tables
-- Table: DETALLE
CREATE TABLE DETALLE (
    IDRESERVA int  NOT NULL,
    IDESTUDIANTE int  NOT NULL,
    ASISTIO int  NOT NULL,
    CONSTRAINT CHK_DETALLE_ASISTIO CHECK (ASISTIO IN (0,1)),
    CONSTRAINT DETALLE_pk PRIMARY KEY  (IDRESERVA,IDESTUDIANTE)
);

-- Table: ESTUDIANTE
CREATE TABLE ESTUDIANTE (
    IDESTUDIANTE int  NOT NULL,
    CONSTRAINT ESTUDIANTE_pk PRIMARY KEY  (IDESTUDIANTE)
);

-- Table: LABORATORIO
CREATE TABLE LABORATORIO (
    IDLABORATORIO int  NOT NULL,
    CONSTRAINT LABORATORIO_pk PRIMARY KEY  (IDLABORATORIO)
);

-- Table: MOTIVO
CREATE TABLE MOTIVO (
    IDMOTIVO int  NOT NULL,
    CONSTRAINT MOTIVO_pk PRIMARY KEY  (IDMOTIVO)
);

-- Table: PROFESOR
CREATE TABLE PROFESOR (
    IDPROFESOR int  NOT NULL,
    CONSTRAINT PROFESOR_pk PRIMARY KEY  (IDPROFESOR)
);

-- Table: RESERVA
CREATE TABLE RESERVA (
    IDRESERVA int  NOT NULL,
    IDPROFESOR int  NOT NULL,
    IDLABORATORIO int  NOT NULL,
    IDMOTIVO int  NOT NULL,
    FECHA date  NOT NULL,
    HORA_INICIO varchar(10)  NOT NULL,
    HORA_FIN varchar(10)  NOT NULL,
    ASISTIERON int  NOT NULL,
    CONSTRAINT RESERVA_pk PRIMARY KEY  (IDRESERVA)
);

-- foreign keys
-- Reference: DETALLE_ESTUDIANTE (table: DETALLE)
ALTER TABLE DETALLE ADD CONSTRAINT DETALLE_ESTUDIANTE
    FOREIGN KEY (IDESTUDIANTE)
    REFERENCES ESTUDIANTE (IDESTUDIANTE);

-- Reference: DETALLE_RESERVA (table: DETALLE)
ALTER TABLE DETALLE ADD CONSTRAINT DETALLE_RESERVA
    FOREIGN KEY (IDRESERVA)
    REFERENCES RESERVA (IDRESERVA);

-- Reference: RESERVA_LABORATORIO (table: RESERVA)
ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_LABORATORIO
    FOREIGN KEY (IDLABORATORIO)
    REFERENCES LABORATORIO (IDLABORATORIO);

-- Reference: RESERVA_MOTIVO (table: RESERVA)
ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_MOTIVO
    FOREIGN KEY (IDMOTIVO)
    REFERENCES MOTIVO (IDMOTIVO);

-- Reference: RESERVA_PROFESOR (table: RESERVA)
ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_PROFESOR
    FOREIGN KEY (IDPROFESOR)
    REFERENCES PROFESOR (IDPROFESOR);

-- End of file.

