-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2024-09-01 03:17:52.41

-- tables
-- Table: RADIO
CREATE TABLE RADIO (
    IDRADIO int  NOT NULL,
    IDUSUARIO int  NOT NULL,
    IDTIPO int  NOT NULL,
    DESCRIPCION varchar(100)  NOT NULL,
    CONSTRAINT RADIO_pk PRIMARY KEY  (IDRADIO)
);

-- Table: SOLICITUD
CREATE TABLE SOLICITUD (
    IDSOLICITUD int  NOT NULL,
    FECHA date  NOT NULL,
    RADIO_IDRADIO int  NOT NULL,
    TECNICO_IDTECNICO int  NOT NULL,
    CONSTRAINT SOLICITUD_pk PRIMARY KEY  (IDSOLICITUD)
);

-- Table: TALLER
CREATE TABLE TALLER (
    IDTALLER int  NOT NULL,
    NOMBRE varchar(100)  NULL,
    DIRECCION varchar(100)  NOT NULL,
    CONSTRAINT TALLER_pk PRIMARY KEY  (IDTALLER)
);

-- Table: TECNICO
CREATE TABLE TECNICO (
    IDTECNICO int  NOT NULL,
    TALLER_IDTALLER int  NOT NULL,
    CONSTRAINT TECNICO_pk PRIMARY KEY  (IDTECNICO)
);

-- Table: TIPO
CREATE TABLE TIPO (
    IDTIPO int  NOT NULL,
    DESCRIPCION varchar(100)  NOT NULL,
    CONSTRAINT TIPO_pk PRIMARY KEY  (IDTIPO)
);

-- Table: USUARIO
CREATE TABLE USUARIO (
    IDUSUARIO int  NOT NULL,
    NOMBRES varchar(100)  NOT NULL,
    APELLIDOS varchar(100)  NOT NULL,
    CONSTRAINT USUARIO_pk PRIMARY KEY  (IDUSUARIO)
);

-- foreign keys
-- Reference: RADIO_TIPO (table: RADIO)
ALTER TABLE RADIO ADD CONSTRAINT RADIO_TIPO
    FOREIGN KEY (IDTIPO)
    REFERENCES TIPO (IDTIPO);

-- Reference: RADIO_USUARIO (table: RADIO)
ALTER TABLE RADIO ADD CONSTRAINT RADIO_USUARIO
    FOREIGN KEY (IDUSUARIO)
    REFERENCES USUARIO (IDUSUARIO);

-- Reference: SOLICITUD_RADIO (table: SOLICITUD)
ALTER TABLE SOLICITUD ADD CONSTRAINT SOLICITUD_RADIO
    FOREIGN KEY (RADIO_IDRADIO)
    REFERENCES RADIO (IDRADIO);

-- Reference: SOLICITUD_TECNICO (table: SOLICITUD)
ALTER TABLE SOLICITUD ADD CONSTRAINT SOLICITUD_TECNICO
    FOREIGN KEY (TECNICO_IDTECNICO)
    REFERENCES TECNICO (IDTECNICO);

-- Reference: TECNICO_TALLER (table: TECNICO)
ALTER TABLE TECNICO ADD CONSTRAINT TECNICO_TALLER
    FOREIGN KEY (TALLER_IDTALLER)
    REFERENCES TALLER (IDTALLER);

-- End of file.

